version: 2
models:
  - name: mart_pet_report
    columns:
    - name: pet_id
      tests:
        - not_null
        - unique
    - name: pet_name
      tests:
        - not_null
    - name: full_name
      tests:
        - not_null
    - name: vaccinated
      tests:
        - accepted_values:
            arguments:
              values: ['Yes', 'No', 'Unknown']




          